### PR TITLE
Update toolchain to gcc-6.30 and uClibc-ng-1.0.22

### PR DESCRIPTION
**Pull request by cbrune**
At a high level this pull request moves the toolchain forward to modern version of the components.  Specifically the new versions are:

- crosstool-NG 1.23.0
- gcc 6.3.0
- uClibc, is now uClibc-ng-1.0.22

Also the default Linux kernel version moved from the 4.1.x series to the 4.9.x series.  The only machine currently using this kernel version is the kvm_x86_64 machine.  All other machine continue to use the same kernel version as before.

To keep machines as they were before I went through and set the versions of Linux and GCC to what they were before as necessary.

For the Linux kernel, where machines were using the default, 4.1.38, I edited the corresponding machine.make to *explicitly* select kernel 4.1.38.  Thus these machines continue to build with their current patch sets.

For older machines that use Linux kernel 3.2.69 the new gcc-6.3.0 will not work.  For these machine I edited the corresponding machine.make to *explicitly* specify gcc-4.9.4, which is the same family as before (old was 4.9.2) but a slightly updated version that crosstools-NG 1.23.0 supports directly.

GCC-6.3.0 does not work directly with the older u-boot versions either, however the patches to make it work are trivial and already upstream in the u-boot project.  Most of the ONIE machines that use the old u-boot are also using kernel 3.2.69, which from the previous paragraph are using the old compiler anyway and no changes are needed.

For machines under my control, like the nxp_p2020 and the armv7a virtual machine I went ahead and patched u-boot 2013.01.01 to work with gcc-6.3.0.  If you are interested in using gcc-6.3.0 with older u-boot consult the u-boot 2013.01.01 patchset.

After all these changes I have verified the following:

- kvm_x86_64  -- using kernel 4.9.33. Compiles and runs in legacy mode and UEFI modes
- dell_s6000_s1220 (x86_64) -- compiles and runs in legacy BIOS mode
- nxp_p2020rdbpca (a PowerPC P2020 eval board, u-boot) -- compiles and runs OK
- accton_as5600_52x (a PowerPC P2020, u-boot, with storage limitations) -- compiles and runs OK
- qemu_armv7a (armv7a virtual machine, u-boot) -- compiles and runs OK
- accton_as4610_54 (dual-core armv7a, u-boot) -- compiles and runs OK
- nxp_ls1043ardb (armv8a, 64-bit ARM) -- compiles. Unable to run as I don't have one

### CODE REVIEW

**Comment by cbrune** [comment]
Pinging @david56 @audihsu-qci @davehu-github @larryming @lakesh-sharma @vincent0083 @mrhpearson @ZhaoQiang-b45475 @shengzhou @pankajbansal3073 

It would be great if the main contributors could take a look at this.  I suggest checking out my branch and spot checking a few of your machines.

**Comment by david56** [comment]
@cbrune ,

The following machines has crosstool-ng compilation error:

- accton_as6710_32x
- accton_as6700_32x
- accton_as5700_96x
- accton_as5710_54x

The error messages are:

    [ERROR]    make[3]: *** [/home/david_yang/onie/build/x-tools/powerpc-softfloat-g6.3.0-lnxfsl-sdk-v1.5-uClibc-ng-1.0.22/build/build/src/linux-fsl-sdk-v1.5/Makefile:912: headers_install] Error 2
    [ERROR]    make[2]: *** [Makefile:130: sub-make] Error 2
    [ERROR]
    [ERROR]  >>
    [ERROR]  >>  Build failed in step 'Installing kernel headers'
    [ERROR]  >>        called in step '(top-level)'
    [ERROR]  >>
    [ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
    [ERROR]  >>        called from: do_kernel_headers[scripts/build/kernel/linux.sh@106]
    [ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
    [ERROR]  >>
    [ERROR]  >>  For more info on this error, look at the file: 'build.log'
    [ERROR]  >>  There is a list of known issues, some with workarounds, in:
    [ERROR]  >>      '/home/david_yang/onie/build/crosstool-ng/crosstool-ng-1.23.0/docs/B - Known issues.txt'
    [ERROR]  >>
    [ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
    [ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
    [ERROR]  >>
    [ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
    [ERROR]  >>  Read the bug reporting guidelines here:
    [ERROR]  >>      http://crosstool-ng.github.io/support/
    [ERROR]
    [ERROR]  (elapsed: 7:56.57)
    gmake[1]: *** [build] Error 2
    gmake[1]: Leaving directory `/home/david_yang/onie/build/x-tools/powerpc-softfloat-g6.3.0-lnxfsl-sdk-v1.5-uClibc-ng-1.0.22/build'
    rm: cannot remove `/home/david_yang/onie/build/x-tools/powerpc-softfloat-g6.3.0-lnxfsl-sdk-v1.5-uClibc-ng-1.0.22/build/.config.2': No such file or directory
    make: *** [/home/david_yang/onie/build/x-tools/powerpc-softfloat-g6.3.0-lnxfsl-sdk-v1.5-uClibc-ng-1.0.22/stamp/xtools-build] Error 1

I try to set `GCC_VERSION = 4.9.4` that still has the same issue.

**Comment by cbrune** [comment]
@david56 - the problem with these machines is they all use the fsl-sdk-v1.5 kernel, which has the problem with deep directory names.  We had to patch crosstool-ng to patch this in the past.  Let me see if that old crosstool-ng patch will work with the  new crosstool-ng.

also this would affect all machines using the fsl-sdk-v1.5 kernel, which includes:
- centec_e580_20q4z
- centec_e580_48x2q4z
- centec_e580_48x6q

**Comment by cbrune** [comment]
@david56 - OK I made a few changes and updated the branch.  The as6710_32x builds OK now.

What changed:

In the past we would patch crosstool-ng directly to work around the "deep directory" path for some of the kernel trees.  Those patches are nasty as they are "diffs of diffs".

Looking more closely at the crosstool-ng configuration options I found options about how packages are extracted and patched.  In particular the options `CT_PATCH_BUNDLED_FALLBACK_LOCAL` and `CT_LOCAL_PATCH_DIR`.

With these options enabled we do not have to patch crosstool-ng directly.  We can point crosstool-ng to a directory that mirrors the `crosstool-ng/patches` directory.  The `CT_PATCH_BUNDLED_FALLBACK_LOCAL` option tells crosstool-ng to first use its own patches and if there are none then it will look at `CT_LOCAL_PATCH_DIR`.  I think that is what we want here.

The updated pull request now adds `patches/crosstool-ng/local/...` as a directory of local patches for crosstool-ng to use.  I updated all the crosstool-ng configs to use  `CT_PATCH_BUNDLED_FALLBACK_LOCAL=y` and `CT_LOCAL_PATCH_DIR`.

In particular I added `patches/crosstool-NG/local/linux/fsl-sdk-v1.5/001-scripts-Makefile.headersinst-install-headers-from-sc.patch` to fix the "deep directory" kernel header problem.

I also did this for Mellanox's kernel by adding patches/crosstool-NG/local/linux/3.10.0-54.0.1.el7.x86_64/0001-kbuild-fix-make-headers_install-when-path-is-too-lon.patch.  It is more or less the same patch, just a different kernel version.

Both of these files are simple patches instead of being a patch of a patch.  Much easier to deal with.

Next - I had to apply one of our previous patches to crosstool-ng directly.  This patch allows the patching of a custom kernel tarball.  The crosstool-ng design skips the application of patches for "custom" tarballs, with their philosophy being that a custom tarball should already be fully patched.  That is not the case for us here as we sometimes use custom tarballs from upstream (like the FSL kernels) that need a little patching.

Finally - the fsl-sdk-v1.5 and 3.10.0-54.0.1.el7.x86_64 kernels do not compile with gcc-6.3.0, so I set the GCC version to 4.9.4 for all machines that use these kernels.

With all that these boards now compile OK.

**Comment by ZhaoQiang-b45475** [comment]
@cbrune ,
I built on nxp_ls2088ardb and there are compilation errors:
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20170628.103336
[INFO ]  Building environment variables
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: do_isl_get[scripts/build/companion_libs/121-isl.sh@833]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@604]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/zhaoq/work/cbrune-check/onie/build/crosstool-ng/crosstool-ng-1.23.0/docs/B - Known issues.txt'
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 0:00.81)
/home/zhaoq/work/cbrune-check/onie/build/crosstool-ng/crosstool-ng-1.23.0/ct-ng:147: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/zhaoq/work/cbrune-check/onie/build/x-tools/armv8a-g6.3.0-lnx4.1.38-glibc-2.25/build'
rm: cannot remove '/home/zhaoq/work/cbrune-check/onie/build/x-tools/armv8a-g6.3.0-lnx4.1.38-glibc-2.25/build/.config.2': No such file or directory
make/xtools.make:117: recipe for target '/home/zhaoq/work/cbrune-check/onie/build/x-tools/armv8a-g6.3.0-lnx4.1.38-glibc-2.25/stamp/xtools-build' failed
make: *** [/home/zhaoq/work/cbrune-check/onie/build/x-tools/armv8a-g6.3.0-lnx4.1.38-glibc-2.25/stamp/xtools-build] Error 1

**Comment by cbrune** [comment]
@ZhaoQiang-b45475 - I did not have any problems building the nxp_ls2088ardb.

The command line I used:
```
make -j24 MACHINEROOT=../machine/nxp/ MACHINE=nxp_ls2088ardb all demo
```
Perhaps the tree was not completely clean.  Try it again after running "make distclean".

**Comment by cbrune** [comment]
@david56 
Accton AS7710_32X compiles now.  Things that had to change:

- use gcc 4.9.4
- patch u-boot-fsl-sdk-v1.7 for GOT table, same patch as u-boot-2013.01.01
- patch Linux fsl-sdk-v1.7 to work with newer binutils.  The newer binutils is more picky about the `cmpi` and `cmpdi` instructions.

Please give that a try.

**Comment by lakesh-sharma** [comment]
> dell_s6000_s1220 (x86_64) -- compiles and runs in legacy BIOS mode

Looks good.

**Comment by ZhaoQiang-b45475** [comment]
hi @cbrune,
I build with update-toolchain branch on your tree(cbrune/onie).
run "make distclean" before compilation, and there still have the same issue.

**Comment by cbrune** [comment]
@ZhaoQiang-b45475  - OK I found the problem.  Try the newly update branch with a distclean.  Thanks for helping with this.

**Comment by cbrune** [comment]
Pushed to master.
